### ISSUE TITLE
GraphQL Language Service server

### ISSUE THREAD

**Issue by asiandrummer** [jimkyndemeyer/js-graphql-language-service#11]
Hi @jimkyndemeyer - I think I reached out to you a while back, but I just wanted to give an update to what I've been working on for the past couple months. The initiative is to provide a general interface for GraphQL Language Service that can support common IDEs to develop their own language service implementation for GraphQL. In addition to the JavaScript API, it supports the RPC server to receive/send messages via streams (the plan is to extend to support other transport protocols in the future). The server is capable of caching the schema/fragment definitions defined on `.graphqlrc` file (uses `fb-watchman` library to caching the file list).

I see you're using `codemirror-graphql` library to power the language service - I think I'm going to have `codemirror-graphql` to depend on features from this language service library, and there might be some expected breaking changes.

My longer-term goal is to enhance the developer experience while working with GraphQL by providing and improving the tools, and for this language service work, implement the language service to common IDEs and build a sort of ecosystem of language services/tools on the open-source community.

I really loved how you're taking initiatives to develop tools for JS and IntelliJ (WebStorm as well). As the release is coming close for this language service I've been working on, I wanted to ask you if you'd like to collaborate with, maybe starting with using this language service for the IntelliJ plugin you have developed already.

I'd also be super interested in just talking about what other things we could do together - let me know if any of this sound good to you :D

**Comment by jimkyndemeyer** [comment]
Hi Hyo.

That's great news. I'd love to collaborate on moving this forward.

My gmail is the same as my github user name, so drop me a line there if you need to reach me outside github.

Thanks,
Jim.

**Comment by asiandrummer** [comment]
@jimkyndemeyer - I'm working to provide a private repo for us to: 1) expose the service for all of us to get familiar, and 2) develop a plan for us to collaborate/adopt the library. Let me invite you to the repo once its ready :p

**Comment by jimkyndemeyer** [comment]
Closing this now that the private repo is up and running.
