### ISSUE TITLE
Throws on comments

### ISSUE THREAD

**Issue by ForsakenHarmony** [jimkyndemeyer/js-graphql-language-service#18]
```
type BatchPayload {
  """
  The number of nodes that have been affected by the Batch operation.
  """
  count: Long!
}
```

```
Syntax Error GraphQL (243:3) Expected Name, found String

242: type BatchPayload {
243:   """
       ^
```

**Comment by ForsakenHarmony** [comment]
bump

**Comment by smmoosavi** [comment]
any update?

**Comment by jimkyndemeyer** [comment]
I' focusing the development efforts on https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/164 which describes the reasoning behind it.

**Comment by jimkyndemeyer** [comment]
Closing this based on https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0 which makes this project obsolete.
