### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by backjo** [jimkyndemeyer/js-graphql-language-service#3]
Stack trace: 
<img width="1048" alt="screen shot 2016-06-05 at 6 49 19 pm" src="https://cloud.githubusercontent.com/assets/2441427/15809961/3ef61d2e-2b4e-11e6-89ff-447db16d1e58.png">

This error is occuring when loading my graphql.json schema file, which is ~4MB (quite a large schema). Looks like express' json parser limit isn't being set, so it's falling back to the default json limit of 100kb. Could this be bumped up to something rather large?

**Comment by jimkyndemeyer** [comment]
Thanks for catching this. I'll bump the limit for the next release.

In the meantime, you can manually patch the js-graphql-language-service.dist.js file mentioned in the stack trace. The relevant code to search for is located at https://github.com/jimkyndemeyer/js-graphql-language-service/blob/master/src/languageservice.js#L97

/Jim.

**Comment by backjo** [comment]
I already did :)

**Comment by jimkyndemeyer** [comment]
Fixed and included in js-graphql-intellij-plugin 1.3.1.

/Jim.
