### ISSUE TITLE
Save schema files

### ISSUE THREAD

**Issue by trbngr** [jimkyndemeyer/js-graphql-language-service#8]
For `babelRelayPlugin` to do its thing, it needs the schema.json file at build-time. It would be great if this service would allow an option to dump the `IntrospectionQuery` result to a file  with configurable path.

Right now I have to have a separate script that fetches the file.

**Comment by jimkyndemeyer** [comment]
Closing this based on https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0 which makes this project obsolete.
